# Makefile to generate tools configuration files

iverilog:
	python arty.py --iverilog ../sim/iverilog_file_list.txt

vivado_sim:
	python arty.py --vivado_sim ../sim/vivado_file_list.txt

vivado_synt:
	python arty.py --vivado_synt ../sim/vivado_file_list.tcl
